local RainP = ParticleType.new("Rain3")
local RainSprite = Sprite.load("Misc/StageObjects/Rain3", 1, 0, 0)
local RotColor = Color.fromHex(0x577248)
RainP:sprite(RainSprite, false, false, false)
RainP:angle(45, 45, 0, 0, false)
RainP:speed(45, 45, 0, 0)
RainP:direction(-45, -45, 0, 0)
local RainSerpentine = Object.new("RainSerpentine")

RainSerpentine:addCallback("step", function(self)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y - 50, 1, RotColor)
end)
