local RainP = ParticleType.find("Rain")
local RotColor = Color.fromHex(0x577248)
RainP:angle(45, 45, 0, 0, false)
RainP:speed(45, 45, 0, 0)
RainP:direction(-45, -45, 0, 0)
local RainSerpentine = Object.new("RainSerpentine")

RainSerpentine:addCallback("step", function(self)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
    RainP:burst("below", camera.x + math.random(1920, -500), camera.y, 1, RotColor)
end)
